targets:
  $default:
    sources:
      - lib/**
      - lib/victoria/swaggers/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/victoria/swaggers'
          output_folder: 'lib/victoria/swagger_generated'
          with_base_url: true
          multipart_file_type: "http.MultipartFile"
