targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/swaggers'
          output_folder: 'lib/swagger_generated'
          with_base_url: true
          include_paths: []
          exclude_paths: []
          build_only_models: false
